export const rows = [
  {
    id: 1,
    name: "Tywin Lannister",
    email: "tywinlannister@gmail.com",
    age: "60",
    phone: "(770)464-1010",
    address: "0912 Won Street , Alabama, SY 10001",
    city: "New York",
    zipCode: "10001",
    registrarId: 123512,
  },
  {
    id: 2,
    name: "Jon Snow",
    email: "jonsnow@gmail.com",
    age: "35",
    phone: "(665)121-5454",
    address: "51234 Fiveton Street, CunFory,ND 111234",
    city: "Colunza",
    zipCode: "111234",
    registrarId: 773116,
  },
  {
    id: 3,
    name: "Cersei Lannister",
    email: "cerseilannister@gmail.com",
    age: "42",
    phone: "(421)314-2288",
    address: "11122 Welping Ave, Tenting, CD 21321",
    city: "Tenting",
    zipCode: "14215",
    registrarId: 183714,
  },
  {
    id: 4,
    name: "Ferrara Frances",
    email: "ferrarafrances@gmail.com",
    age: "44",
    phone: "(543)124-0123",
    address: "4123 Easer Blvd , Wentington,AD 44215",
    city: "Colunza",
    zipCode: "44215",
    registrarId: 533215,
  },
  {
    id: 5,
    name: "Arya Stark",
    email: "aryastark@gmail.com",
    age: "16",
    phone: "(921)425-6742",
    address: "11122 Awesome Street, Colunza CD 21321",
    city: "Colunza",
    zipCode: "1234",
    registrarId: 123216,
  },
  {
    id: 6,
    name: "Ever Melisandre",
    email: "evermelisandre@gmail.com",
    age: "150",
    phone: "(232)545-6583",
    address: "1235 Canvile Street, Esvazark, NY 10001",
    city: "Esvazark",
    zipCode: "10001",
    registrarId: 593278,
  },
  {
    id: 7,
    name: "Jamie Lannister",
    email: "jamielannister@gmail.com",
    age: "45",
    phone: "(422)982-6793",
    address: "22215 Super Street, Esvazrk ,NY 12154",
    city: "Esvazrk",
    zipCode: "12154",
    registrarId: 933995,
  },
  {
    id: 8,
    name: "Rossini Frances",
    email: "rossinifrances@gmail.com",
    age: "36",
    phone: "(222)444-5555",
    address: "46518 Grey Street, New York , 71457",
    city: "New York",
    zipCode: "71457",
    registrarId: 197134,
  },
];
export const columns = [
  {
    field: "id",
    headerName: "ID",
    headerAlign: "center",
    align: "center",
    width: 50,
  },
  {
    field: "name",
    headerName: "Name",
    width: 150,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "email",
    headerName: "Email",
    flex: 1,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "age",
    headerName: "Age",
    headerAlign: "center",
    align: "center",
    width: 50,
  },
  {
    field: "address",
    headerName: "Address",
    flex: 1,
    headerAlign: "center",
    align: "center",
  },
  {
    field: "city",
    headerName: "City",
    headerAlign: "center",
    align: "center",
  },
  {
    field: "zipCode",
    headerName: "ZipCode",
    headerAlign: "center",
    align: "center",
  },
];
